import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
//Global CSS can be imported in _app.js only...
// import "../styles/globals.css";
import Link from "next/link";
{/* 
  Difference between anchor and link is that anchor is used to navigate to other pages with reloading and link is used to navigate to other pages without refreshing the page.  
*/}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keyword" content="nextjs, hunting coder, blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"> */}
        {/* 
          strategy: examples --> afterInteractive, beforeInteractive (loads script before), lazyOnload (loads script after page load)
         */}
      {/* </Script> */}
      {/* <Image> */}
        {/* By default lazy loaded and optimizes provided image. */}
      {/* </Image> */}
      <nav className={styles.mainnav}> {/* Class name directly is not allowed instead use className = {styles.yourName} */}
        <ul>
          <Link href="/"><li>Home</li></Link>
           <Link href="/about"><li>About</li></Link>
           <Link href="/blog"><li>Blog</li></Link>
           <Link href="/contact"><li>Contact</li></Link>
        </ul>
      </nav>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1 className={styles.title}>
            Hunting Coder
          </h1>
          <p className={styles.description}>
            A blog for Hunting coders by a hunting coder
          </p>
          <div className="blogs">
            <h2>Popular Blogs</h2>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2024?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2024?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2024?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2024?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
          </div>
        </main>
        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}
