import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
    <style jsx>{`
        h2{
          font-size: 38px;
        }
        h3{
          font-size: 28px;
        }
      `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keyword" content="nextjs, hunting coder, blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1 className={styles.title}>
            Hunting Coder
          </h1>
          <div className={styles.imgWrapper}>
            <Image className={styles.myImg} src="/homeimg.jpg" width={518} height={354} />
          </div>
          <p className={styles.description}>
            A blog for Hunting coders by a hunting coder
          </p>
          <div className="blogs">
            <h2>Latest Blogs</h2>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2024?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2024?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2024?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2024?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
          </div>
        </main>
        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}
